deckhouse/dmt

.gitignore, cmd/dmt/main.go, internal/flags/flags.go
Two sub-tees were added:
- lint
- gen
By default, we output a use reference.
=> feat: add subcommands

.gitignore, cmd/dmt/main.go, internal/flags/flags.go, internal/logger/logger.go
After the improvements, the logger initialization turned out to be before the flags were parsed. As a result, we have always used the INFO logging level.
In order to fix the situation, it was necessary to move the logger initialization to the place after parsing the command line flags.
=> fix: set log level

internal/module/openapi.go
When parsing openapi spec, if we encounter an enum field, we take this value unchanged. While you expect the string data type to be used. As a result, we got an error.
These changes correct the situation. If a default value is set, it is used. Otherwise, the first value from the enumeration is taken.
Tested locally. Helm parsing errors are no longer observed.
=> fix: improve parsing openapi enum keys

cmd/dmt/main.go
When using relative paths, we had panics during processing. The problem is that we pass paths without processing as is. And openapi has additional processing of these paths.
Added conversion of module paths to absolute paths.
=> fix: panic with relative paths

internal/module/openapi.go
Changed behavior for loading image digests file:
- If found `imageDigestfile`  in module directory, load all values with default ones
- Otherwise load default generated only.
=> fix: Fixed image digests load for downloaded modules

pkg/linters/helm/rules/images.go
While checking the module template, we got a validation error in the helm linter:
```plain
🐒 [#helm]
Message    - ealen/echo-server:0.7.0%!!(MISSING)(EXTRA string=Last `FROM` instruction should use one of our $BASE_DISTROLESS images)
Object    - echoserver
Module    - echoserver
Value    - module = echoserver, image = echoserver/Dockerfile
```
Which is not correct and it is necessary to correct the format of the output of these errors.
It is likely that the reason is the incorrect use of the error generation function.
After the changes, the error is displayed:
```plain
🐒 [#helm]
Message	- Last `FROM` instruction should use one of our $BASE_DISTROLESS images
Object	- echoserver
Module	- module = echoserver, path = echoserver/Dockerfile
Value	- ealen/echo-server:0.7.0
```
=> fix: error message for image check

internal/module/module.go, internal/module/openapi.go
Fixed: #39 
1. I missed another case of using helm_lib_module_, which caused a digest generation error. There is no error on trivy now.
2. If we set the cniSecretData variable, it is expected that its value will be in base64 format. Since we generate random values for strings, this is not the case. As a result, the output was a string in an incorrect format, which helm could not reproduce. We had to exclude the variable from the spec so that new values could be generated in cloud-providers.
=> fixes parsing openapi spec for some modules

.gitignore, internal/manager/manager.go
When creating a module, we may encounter various errors. They are displayed as text in the logs, but do not affect the operation of the linter. As a result, we show the error but do not block the build if such an error occurs. And it won't be fixed.
A change is proposed; module creation errors are now added to the general list and are critical. That is, if an error occurs when creating a module, it will now be displayed in the general list in the same format, and the linter will exit with code 1.
Example:
```plain
🐒 [#manager]
Message - cannot create module
Object  - /deckhouse/modules/011-flow-schema
Module  - 011-flow-schema
Value   - error evaluating symlink /deckhouse/modules/011-flow-schema/charts/helm_lib: lstat /Users/devsyukov/src/github.com/deckhouse/deckhouse/deckhouse: no such …
```
=> feat: critical error on creating module

pkg/linters/rbac/roles/placement.go
When running the linter, a large number of errors are displayed in rbac:
```
🐒 [#rbac]
Message	- kind d8:cloud-provider-vsphere:cloud-controller-manager not allowed in "templates/cloud-controller-manager/rbac-for-us.yaml"
Object	- kind = ClusterRole ; name = d8:cloud-provider-vsphere:cloud-controller-manager
Module	- cloud-provider-vsphere
```
But in reality everything is correct.
The code checked the name of an object named Kind. You need to check the Kind of the object.
=> fix: get kind for rbac linter

pkg/linters/container/container.go, pkg/linters/container/rules.go, pkg/linters/images/rules/images.go, pkg/linters/rbac/rbac.go, pkg/linters/rbac/roles/binding-subject.go, pkg/linters/rbac/roles/placement.go, pkg/linters/rbac/roles/wildcards.go
After the changes, the module name is now displayed correctly in error messages:
```
🐒 [#rbac]
Message - kind cloud-data-discoverer not allowed in "templates/cloud-data-discoverer/rbac-for-us.yaml"
Object  - kind = ServiceAccount ; name = cloud-data-discoverer ; namespace = d8-cloud-provider-vsphere
Module  - cloud-provider-vsphere
```
fixed: #38
=> Object identification in log messages

internal/helm/render.go, internal/storage/storage.go, pkg/linters/container/rules.go, pkg/linters/images/rules/images.go, pkg/linters/k8s-resources/crds.go, pkg/linters/k8s-resources/rules.go, pkg/linters/monitoring/rules.go, pkg/linters/rbac/roles/binding-subject.go, pkg/linters/rbac/roles/wildcards.go
refactor: consolidate duplicate code
added checks for readonly filesystem on containers (fixed: https://github.com/deckhouse/deckhouse/issues/4690)
remove panics
=> feat: check readonly filesystem on containers

internal/logger/logger.go
We refuse to use a global variable and use the slog functionality.
=> feat: improve logging

README.md, internal/manager/manager.go, pkg/config/linters_settings.go, pkg/linters/conversions/conversions.go, pkg/linters/conversions/rules.go
Add conversion linter
Checks:
1) 'openapi/conversions' folder exists
2) for every file in folder 'openapi/conversions' with name pattern 'v0.yaml' or 'v0.yml'
2.1) file not empty
2.2) version is not empty
2.3) filename correspond with version in file
2.4) description filled for ru and eng
3) parsed versions from files exists
4) first version equals 'first-version' rule in '.dmtlint .yaml'. if rule equals 0 or not filled - skip this check
5) check sequence of conversion versions, if it has break sequential versions like '2,3,5,6' - linter throw error
Rules:
```yaml
conversions:
skip-check:
- flow-schema
first-version: 2
```
=> [linter] add conversion linter

pkg/linters/images/rules/images.go, pkg/linters/images/rules/rules.go
fixed: #60 
example output:
```plain
🐒 [#images]
Message - Image name format should be like `image: {{ .ModuleName }}/{{ .ImageName }}[-something]` in file: terraform-manager-yandex/werf.inc.yaml
broken lines:
image: terraform-provider-yandex
Object  - terraform-manager-yandex/werf.inc.yaml
Module  - terraform-manager
```
=> feat: add image name validation rule for werf files

internal/module/loader.go, internal/module/module.go, internal/module/sympath.go, pkg/linters/conversions/conversions.go, pkg/linters/conversions/rules.go
We have an error like:
```
🐒 [#manager]
Message - cannot create module `600-namespace-configurator`
Object  - /deckhouse/modules/600-namespace-configurator
Module  - 600-namespace-configurator
Value   - Chart.yaml file is missing
```
because Deckhouse doesn't require the Chart.yaml file. It will create it automatically. But chart parsing requires this file, so we have to implement out custom loader, based on helm DirLoader.
Also fixes the error:
```
🐒 [#conversions]
Message - Conversions folder is not exist, at path "openapi/conversions": stat /deckhouse/modules/600-namespace-configurator/openapi/conversions: no such file or directory
Object  - namespace-configurator
Module  - namespace-configurator
```
=> Add custom module chart loader

internal/manager/manager.go, internal/module/module.go, internal/module/openapi.go, internal/module/openapi_test.go, internal/module/templates/_module_image.tpl, internal/module/templates/_module_name.tpl, internal/valuesvalidation/global-openapi/values.yaml, pkg/linters/container/rules/container_image_digest_check.go, pkg/linters/templates/rules/grafana.go, pkg/linters/templates/rules/prometheus_rules_test.go
Previously, we had helmet template hacks that were implemented through string replacement. Quite sloppy, which led to a number of errors in the generation diagrams. Since we use the lint generation launch mode, we did not notice these errors. But this does not mean that this did not affect the work.
The current changes allow us to replace additional functions for generating an image digest in such a way that the templates change minimally. But in the end, we get the correct result for any modules and almost any diagrams. As an exception, controlPlaneManager was given here, which needed to describe global values. But for now this leads to the conclusion.
The logic of image digest verification for containers was also corrected. Now it works correctly for the results that we have when …
=> feat: change processing helm chart with remaping templates

internal/manager/manager.go, pkg/config/config.go, pkg/config/linters_settings.go, pkg/errors/errors.go, pkg/level.go
Add max level for manager (to have error level permanently)
Error handling behavior:
1) if has no global or module value - Error lvl
2) if has no global value, but has module value - set from module
3) if has global value and module value - set from global
4) if has global value, but has no module value - set from global
Error sorting behavior:
1) Sort by module
2) Sort by linter
3) Sort by rule
=> fix error level behavior

pkg/linters/module/rules/license.go
Skip totally empty files like `placeholder`
=> Skip empty files

.golangci.yml, internal/module/module.go, pkg/linters/container/rules/dns_policy.go, pkg/linters/images/images_rules.go, pkg/linters/module/rules/module_yaml.go, pkg/linters/templates/rules/vpa.go
Get module namespace from the module.yaml file and then, if empty, fallback to the `.namespace` file
=> Fix module namespace generation

internal/module/openapi.go
We use some variables of the string type to store data in base64 format. This value is decoded in templates. And if it's not base64, we get an error.
For such cases, we will generate string values by key name, encoding it in base64 format. And if decoding is used in the template, there will be no errors.
Such a change allows you to simplify the processing of openapi by removing the hardcode for the variable value.
=> refactor: simplify string parsing by encoding keys in base64

internal/fsutils/getfiles.go
When filtering files for Openapi, we take the full path, but in the regexp we check the relative one. We fix the error by passing the required path.
=> fix: update file path handling in GetFiles function

cmd/dmt/main.go, internal/flags/flags.go, internal/manager/manager.go, internal/metrics/convert.go, internal/metrics/metrics.go, internal/metrics/service.go, internal/metrics/storage.go, internal/promremote/promremote.go, pkg/config/global/global.go
=> add telemetry

internal/fsutils/fsutils.go, internal/manager/manager.go, internal/manager/validate.go, internal/module/module.go, pkg/linters/module/rules/conversions.go
We have situations where we try to create a module before launching linters. But the creation ends in an error due to the inability to assemble helm or openapi due to the lack of a number of configuration parameters.
In order to get more readable errors, we enable the check for the presence of the `name` and `namespace` fields in module.yaml, the `name` field in the Chart.yaml file, and the presence of the correct openapi directory. If an error occurs during validation, we do not create a module, and in logs we output errors of the form:
```
time=2025-04-02T11:50:21.808+03:00 level=INFO msg="DMT version: development"
time=2025-04-02T11:50:21.808+03:00 level=INFO msg="Dir: /Users/devsyukov/src/github.com/deckhouse/sds-local-volume"
time=2025-04-02T11:50:47.520+03:00 level=INFO msg= "Found …
```
=> feat: add module validation logic in manager

internal/manager/validate.go
We lost information about the module name in the validation error output. As a result, we don't know the module name and we don't know the path where the error occurred.
```plain
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty
Module:      
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty
Module:      
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty
Module:      
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty
Module:      
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty
Module:      
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty
Module:      
🐒 [definition-file (#module)]
Message:     module.yaml `namespace` is empty …
```
=> feat: include file path in module validation error reporting

internal/module/openapi.go
```
🐒 [(#manager)]
Message:      cannot create module `xxx`
Module:       xxxx
Value:        cannot find openapi values schema for module xxx
FilePath:     /deckhouse/modules/xxx
```
have no information about the error. Add some verbosity
=> Add verbose error

pkg/linters/module/rules/module_yaml.go, pkg/linters/module/rules/module_yaml_test.go
```
🐒 [definition-file (#module)]
Message:      Field 'name' must be less than 64 characters
Module:       cniciliumsdfsdfsdfsdfdsfsdfsdfsdfsdfsdfssdfsdfsdfsdfsdfsdfsfdsfsdfdsfsss
FilePath:     module.yaml
```
=> feat: enforce maximum length for module 'name' to 64 characters

.github/workflows/checks.yml, .golangci.yml, internal/engine/files.go, internal/manager/validate_test.go, internal/metrics/metrics_test.go, internal/module/openapi.go, internal/werf/werf.go, pkg/linters/images/rules/distroless.go, pkg/linters/images/rules/image.go, pkg/linters/rbac/rules/placement.go
This pull request introduces updates to improve code quality, enhance maintainability, and align with modern practices. Key changes include upgrading the linter configuration, renaming variables for clarity, replacing deprecated assertions in tests, and simplifying logic in various functions.
* Updated `.github/workflows/checks.yml` to use `golangci-lint-action@v8` with version `v2.1` for improved linter capabilities.
* Overhauled `.golangci.yml` to enable a broader set of linters, refine settings, and improve maintainability. This includes enabling linters like `staticcheck`, `errorlint`, and `gocritic`, while removing outdated configurations.
* Renamed variables in `internal/module/openapi.go` (e.g., `values` to `helmValues`) for better clarity and alignment with their purpose. …
=> feat: update golangci-lint to v2.1

.github/workflows/coverage-badge.yml, README.md, coverage.svg, internal/engine/engine.go, internal/engine/engine_test.go, internal/engine/files_test.go, internal/engine/funcs.go, internal/engine/funcs_test.go, internal/module/camel_test.go, internal/openapi/parser_test.go, internal/storage/storage_test.go, internal/values/values.go, internal/values/values_test.go, pkg/linters/no-cyrillic/rules/files.go, pkg/linters/no-cyrillic/rules/files_test.go, pkg/linters/templates/rules/prometheus_rules_test.go
This pull request introduces several key updates, including a new GitHub Actions workflow for updating test coverage badges, improvements to the Helm engine implementation, and enhancements to documentation and testing. Below are the most significant changes grouped by theme.
* Added a new GitHub Actions workflow (`.github/workflows/coverage-badge.yml`) to automatically update the test coverage badge in the `README.md` file. This includes steps to run tests, generate a coverage report, and dynamically create a badge based on the coverage percentage.
* Updated the `README.md` to include a dynamic coverage badge and improved formatting for sections like "Lint" and "Gen". [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3-R35) …
=> feat: rename initFunMap to initFuncMap and add comprehensive tests for Engine functionality

pkg/config/linters_settings.go, pkg/linters/templates/README.md, pkg/linters/templates/rules/grafana.go, pkg/linters/templates/templates.go
This pull request introduces a new configuration option to disable the Grafana Dashboards rule in the linter settings. The changes include updates to the configuration structure, rule initialization, and documentation.
* [`pkg/config/linters_settings.go`](diffhunk://#diff-cb1fbdbfccd3fd0d8fe9d9006138fbcd1afcc3a701b37180c6fe50ed0c5c390fR167): Added `GrafanaDashboards` to `TemplatesSettings` and defined a new `GrafanaDashboardsExcludeList` type with a `Disable` field. This allows users to configure the exclusion of the Grafana Dashboards rule. [[1]](diffhunk://#diff-cb1fbdbfccd3fd0d8fe9d9006138fbcd1afcc3a701b37180c6fe50ed0c5c390fR167) [[2]](diffhunk://#diff-cb1fbdbfccd3fd0d8fe9d9006138fbcd1afcc3a701b37180c6fe50ed0c5c390fR179-R182)
* …
=> feat: add grafana dashboards exclusion settings and update related logic

internal/engine/engine.go, internal/engine/engine_test.go, internal/module/openapi.go, pkg/linters/openapi/rules/enum.go, pkg/linters/openapi/rules/keys.go
This pull request includes several changes to improve error handling and robustness in the codebase. The most important updates address cases where empty values or slices could lead to unexpected behavior, ensuring proper handling of edge cases.
* [`internal/engine/engine.go`](diffhunk://#diff-c9a29ac513b03b203827d19beb65f9eff05111842ab545c071f25a656f998fc4R285-R289): Updated the `render` function to handle cases where the buffer is empty by setting `rendered[filename]` to an empty string instead of attempting replacements, ensuring graceful handling of nil pointer errors and missing values. [[1]](diffhunk://#diff-c9a29ac513b03b203827d19beb65f9eff05111842ab545c071f25a656f998fc4R285-R289) [[2]](diffhunk://#diff-c9a29ac513b03b203827d19beb65f9eff05111842ab545c071f25a656f998fc4R299-R303)
* …
=> fix: handle nil and empty cases in template rendering and parsing logic

pkg/linters/openapi/rules/crds.go, pkg/linters/openapi/rules/crds_test.go
This pull request includes a small change to the `DeckhouseCRDsRule` linter in the `pkg/linters/openapi/rules/crds.go` file. The change removes the validation of the "heritage" label for CRDs, simplifying the label validation logic.
=> fix: remove validation for 'heritage' label in CRD rule

internal/werf/werf.go
Previously, we used the EE edition by default to generate werf.
In order to properly test the CSE edition, we need to have the ability to change the edition when running the check.
In this change, we check the value of the environment variable WERF_ENV, and if it is not empty, we use its value. Otherwise, we set the EE edition by default.
=> feat: update WERF_ENV retrieval in GetWerfConfig function

pkg/linters/templates/rules/registry.go, pkg/linters/templates/rules/registry_test.go
Let's change the dmt condition, it should be triggered only if it has found the condition `.dockerconfigjson: {{ .Values.global.modulesImages.registry.dockercfg }}` and did not find the condition `.dockerconfigjson: {{ .Values.<module-name>.registry.dockercfg }}`
Example:
```plain
🐒 [registry (#templates)]
Message:     registry-secret.yaml file contains .Values.global.modulesImages.registry.dockercfg but missing
.Values.userAuthn.registry.dockercfg
Module:      user-authn
🐒 [registry (#templates)]
Message:     registry-secret.yaml file contains .Values.global.modulesImages.registry.dockercfg but missing
.Values.userAuthz.registry.dockercfg
Module:      user-authz
```
=> feat: enhance registry secret validation and add new test cases

pkg/linters/container/rules/container_check_read_only_root_filesystem.go
We need to remove volume mounts check before readonlyfs
When a container has `ReadOnlyRootFilesystem: true` but **no volume mounts**, it provides:
1. **Maximum Security Hardening**
- Prevents any runtime modifications to the container's filesystem
- Blocks malicious code from writing persistent files
- Eliminates container escape vectors through filesystem manipulation
2. **Immutable Infrastructure**
- Ensures the container runs exactly as built in the image
- Prevents configuration drift during runtime
- Supports the principle of immutable deployments
3. **Attack Surface Reduction**
- Prevents malware from persisting files to disk
- Blocks privilege escalation attempts via filesystem modifications
- Reduces impact of compromised containers
When a container has `ReadOnlyRootFilesystem: …
=> [dmt] remove volume mounts check

pkg/linters/module/README.md, pkg/linters/module/rules/module_yaml.go, pkg/linters/module/rules/module_yaml_test.go
With the introduction of [Deckhouse PR #14978](https://github.com/deckhouse/deckhouse/pull/14978), modules can now define version jump paths to enable controlled upgrades between releases.
This PR implements comprehensive validation for the new `update` section in Deckhouse module definitions (`module.yaml`). The `update` section allows modules to define version jump paths for controlled upgrades between releases.
1. **Added data structures** for `update` section:
- `ModuleUpdate` struct with `Versions` array
- `ModuleUpdateVersion` struct with `From` and `To` fields
2. **Implemented validation logic** (`validateUpdate` function):
- Required fields validation (`from` and `to` must be present)
- Version format validation (only `major.minor`, patch versions forbidden)
- Version comparison …
=> [dmt] Add update field validations

pkg/linters/docs/rules/bilingual.go, pkg/linters/docs/rules/cyrillic_in_english.go, pkg/linters/docs/rules/readme.go
The documentation linter only checked for the presence of README.md / README_RU.md pairs in the module root and/or in docs/, plus a few special conditions for empty files. This did not cover the rest of the documentation and did not work as intended.
We limited the scope of the check to the module's docs/ folder.
- Checks are only run if <module>/docs exists. The module root (<module>/README*.md) is no longer part of this rule.
We expanded the check to all documentation files in docs/.
The linter collects all *.md files in docs/ and builds correspondences:
- Any file ending in .ru.md is considered the Russian version.
- Any file ending in .md but not .ru.md is considered the English version.
- For each English version (n).md, a pair (n).ru.md is required. The prefix must be strictly .ru …
=> Fix documentation linter

pkg/linters/docs/rules/bilingual.go, pkg/linters/docs/rules/cyrillic_in_english.go
Documentation should be checked only in the /docs directory without subfolders.
=> [dmt] Documentation linter must checks only in /docs directory

pkg/linters/docs/rules/bilingual.go, pkg/linters/docs/rules/cyrillic_in_english.go
Currently, deckhouse contains many files with names *_RU.md
This leads to multiple errors and it is impossible to rename them quickly and without problems.
At the moment, we ignore such files in order not to cause problems in deckhouse and plan to remove this fallback in the future.
=> [dmt] Ignore "_RU.md" documentation

pkg/linters/module/rules/license.go
We should not check license files if they are empty.
File data: Nil
Before:
```
🐒 [license (#module)]
Message:      unsupported file type:
%filepath%
Module:       %modulename%
FilePath:     %filepath%
```
After:
No errors
=> [dmt] Fix empty license check
