- cmd/dmt/main.go
- internal/manager/manager.go
- internal/module/module.go
- pkg/config/loader.go
> feat: improve settings and error handling

- cmd/dmt/main.go
https://github.com/deckhouse/deckhouse/actions/runs/11837271946/job/32983943751?pr=10650
> feat: enable colors in github actions

- internal/valuesvalidation/global-openapi/config-values.yaml
- internal/valuesvalidation/global-openapi/values.yaml
- internal/valuesvalidation/values_validation.go
> feat: embed global openapi spec

- go.mod
- go.sum
- internal/module/openapi.go
- internal/module/openapi_test.go
> openapi spec: correct use of examples

- internal/module/module.go
> fix: change static image digest to imageHash-<module-name>-container

- cmd/dmt/main.go
- pkg/config/config.go
- pkg/errors/errors.go
Close https://github.com/deckhouse/dmt/issues/46
> Color only-warning messages

- internal/manager/manager.go
- pkg/config/linters_settings.go
- pkg/linters/ingress/ingress.go
- pkg/linters/ingress/rules.go
fixed: https://github.com/deckhouse/deckhouse/issues/4339
Adding a linter to check for the presence of the copy_custom_certificate hook in the ingress object.
> feat: add ingress linter with custom certificate rule checks

- go.mod
- internal/manager/manager.go
- internal/module/module.go
- pkg/config/linters_settings.go
- pkg/linters/images/rules/rules.go
- pkg/linters/module/module.go
- pkg/linters/module/rules.go
> add validate module.yaml file

- .golangci.yml
- internal/helm/render.go
- internal/module/controller.go
- internal/module/module.go
- pkg/linters/container/container.go
- pkg/linters/container/rules.go
- pkg/linters/images/images.go
- pkg/linters/images/rules/images.go
- pkg/linters/images/rules/rules.go
- pkg/linters/ingress/ingress.go
- pkg/linters/k8s-resources/pdb/pdb.go
- pkg/linters/k8s-resources/rbac-proxy/kube-rbac-proxy-ca.go
- pkg/linters/k8s-resources/resources.go
- pkg/linters/k8s-resources/rules.go
- pkg/linters/k8s-resources/vpa/vpa.go
- pkg/linters/module/module.go
- pkg/linters/module/rules.go
- pkg/linters/monitoring/monitoring.go
- pkg/linters/monitoring/prometheus_rules.go
- pkg/linters/probes/probes.go
- pkg/linters/rbac/rbac.go
> added nonamedreturns

- internal/manager/manager.go
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/linters/container/rules.go
- pkg/linters/images/rules/images.go
- pkg/linters/images/rules/werf.go
- pkg/linters/k8s-resources/crds.go
- pkg/linters/k8s-resources/pdb/pdb.go
- pkg/linters/k8s-resources/rbac-proxy/kube-rbac-proxy-ca.go
- pkg/linters/k8s-resources/rules.go
- pkg/linters/k8s-resources/vpa/vpa.go
- pkg/linters/license/license.go
- pkg/linters/monitoring/rules.go
- pkg/linters/no-cyrillic/no-cyrillic.go
- pkg/linters/openapi/openapi.go
- pkg/linters/probes/probes.go
- pkg/linters/rbac/roles/placement.go
Recent changes in error handling have led to the fact that any use of With methods changes all parent objects. Which leads to the fact that in multi-threaded processing we get incorrect results. That is, the result is tied to another object.
The current changes are designed to solve this problem by creating new objects each time using the With methods. We have only one variable that passes through all objects, this is the result slice.
Tests have been added to check the current logic of work.
> Improved error handling

- pkg/linters/no-cyrillic/no-cyrillic.go
> feat: extend skip document regex to include openapi conversions

- internal/manager/manager.go
- pkg/config/linters_settings.go
- pkg/errors/errors.go
- pkg/linters/conversions/rules.go
- pkg/linters/no-cyrillic/no-cyrillic.go
1. Changing the module definition
2. If the Object is empty, do not display it
3. New methods: WithFilePath and WithLineNumber
4. Configuration constants in no-cyrillic
> refactor-1

- pkg/config/linters_settings.go
- pkg/linters/monitoring/README.md
- pkg/linters/monitoring/monitoring.go
- pkg/linters/monitoring/prometheus_rules.go
- pkg/linters/monitoring/rules.go
> Fix monitoring linter

- pkg/linters/container/container.go
- pkg/linters/container/rules.go
> [container] refactor linter

- pkg/linters/module/rules/module_yaml.go
- pkg/linters/no-cyrillic/rules/files.go
Linked with https://github.com/deckhouse/deckhouse/pull/12189
> Handle module descriptions

- internal/module/templates/_module_image.tpl
> feat: add functions to retrieve image digests with and without failure

- internal/module/openapi.go
- internal/module/openapi_test.go
Add default value for `.Values.myModule.registry.dockercfg`
> feat: add default module registry setup in OpenAPI configuration

- internal/module/controller.go
- pkg/linters/container/rules/priority_class.go
- pkg/linters/module/rules/license_library.go
- write the template path on yaml render template
- ignore .github in license check
- add more priorityClasses
> Some improvements

- pkg/linters/hooks/rules/rules.go
Correction of the logic of checking for copy_custom_certificate rules.
https://flant.kaiten.ru/47809880
> refactor: improve hook file filtering logic in rules.go

- pkg/linters/templates/rules/kube_rbac_proxy_ca.go
https://flant.kaiten.ru/47809692
> feat: skip non-deckhouse namespaces in kube_rbac_proxy_ca

- go.mod
- internal/manager/manager.go
- internal/metrics/metrics.go
Add metrics handling for each error occured in linter.
Handle only warn level
Handle warn, error, critical levels
> [dmt] add telemetry for all error levels

- internal/flags/flags.go
- internal/manager/manager.go
- internal/module/controller.go
- internal/storage/storage.go
- internal/storage/storage_test.go
- pkg/level.go
- pkg/linters/container/rules.go
- pkg/linters/container/rules/container_check_read_only_root_filesystem.go
- pkg/linters/container/rules/container_resources.go
- pkg/linters/container/rules/container_security_context.go
- pkg/linters/container/rules/dns_policy.go
- pkg/linters/container/rules/probes.go
- pkg/linters/container/rules_test.go
- pkg/linters/hooks/rules/rules.go
- pkg/linters/images/rules/patches.go
- pkg/linters/images/rules/werf.go
- pkg/linters/module/rules/conversions.go
- pkg/linters/module/rules/helmignore.go
- pkg/linters/module/rules/module_yaml.go
- pkg/linters/module/rules/module_yaml_test.go
- pkg/linters/module/rules/oss_library.go
- pkg/linters/rbac/rules/binding-subject.go
- pkg/linters/rbac/rules/user-authz.go
- pkg/linters/rbac/rules/wildcards.go
- pkg/linters/templates/rules/grafana.go
- pkg/linters/templates/rules/ingress.go
- pkg/linters/templates/rules/kube_rbac_proxy_ca.go
- pkg/linters/templates/rules/pdb.go
- pkg/linters/templates/rules/prometheus_rules.go
- pkg/linters/templates/rules/service_port.go
This PR introduces a comprehensive overhaul of DMT's path handling and output filtering system, enabling better tool integration and flexible user experience through configurable verbosity and path presentation modes.
- **Smart Path Resolution**: New `GetPath()` method respects global `--abs-path` flag preference
- **New `Ignored` Level**: Extends hierarchy to `Ignored → Warn → Error → Critical`
- **Level-Based Filtering**: Manager now filters output based on error levels and user flags
- **Handle ignored cases**: All ignored cases now will be analyzed and stored as errors with Ignored level
```bash
--abs-path      # Enable absolute filesystem paths in error outputs
--hide-warnings # Filter out warning-level messages  
--show-ignored  # Display suppressed/ignored rule violations
``` …
> [dmt] Comprehensive Output Control

- pkg/linters/module/README.md
- pkg/linters/module/rules/license_parser.go
- Add SPDX license pattern
- Fix fatal error with Start-End index
- Make YearPattern optimal
> [dmt] Add SPDX license and some fixes
